add wave sim:/exec_tb/clk
add wave sim:/exec_tb/reset
add wave sim:/exec_tb/flush
add wave sim:/exec_tb/stall
add wave sim:/exec_tb/op
add wave sim:/exec_tb/pc_in
add wave sim:/exec_tb/pc_new_out
add wave sim:/exec_tb/pc_old_out
add wave sim:/exec_tb/wrdata
add wave sim:/exec_tb/wbop_in
add wave sim:/exec_tb/memop_in
add wave sim:/exec_tb/aluresult
add wave sim:/exec_tb/exec_inst/alu_A
add wave sim:/exec_tb/exec_inst/alu_B
add wave sim:/exec_tb/exec_inst/alu_Z
add wave sim:/exec_tb/exec_inst/alu_A_2
add wave sim:/exec_tb/exec_inst/alu_B_2
add wave sim:/exec_tb/exec_inst/alu_Z_2
add wave sim:/exec_tb/exec_inst/alu_R_2
