add wave sim:/ctrl_tb/clk
add wave sim:/ctrl_tb/reset
add wave sim:/ctrl_tb/exec_op
add wave sim:/ctrl_tb/wb_op_mem
add wave sim:/ctrl_tb/pcsrc_in
add wave sim:/ctrl_tb/uut/int_pcsrc_in
add wave sim:/ctrl_tb/stall
add wave sim:/ctrl_tb/uut/critical_reg
add wave sim:/ctrl_tb/uut/st_cnt
add wave sim:/ctrl_tb/stall_fetch
add wave sim:/ctrl_tb/stall_dec
add wave sim:/ctrl_tb/stall_exec
add wave sim:/ctrl_tb/stall_mem
add wave sim:/ctrl_tb/stall_wb
add wave sim:/ctrl_tb/flush_fetch
add wave sim:/ctrl_tb/flush_dec
add wave sim:/ctrl_tb/flush_exec
add wave sim:/ctrl_tb/flush_mem
add wave sim:/ctrl_tb/flush_wb
